active-profile: local
spring:
  profiles:
    active: '@activatedProperties@'
  jmx:
    enabled: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: database
      authentication-database: admin
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

