version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: be-chapter-mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
        - ./mongodb/database:/data/db
    ports:
        - 27017:27017
